import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import StoreProvider from '@/lib/Provider/StoreProvider';
import { SideNav } from '@/common/components/SideNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next Redux Typescript Tailwind',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        {/* Wrapper for flex layout */}
        <div className="flex min-h-screen">
          {/* Sidebar */}
          <aside className="w-64 h-screen text-white fixed">
            <SideNav />
          </aside>

          {/* Main content */}
          <main className="ml-64 flex-1 p-4">{children}</main>
        </div>
      </StoreProvider>
    </html>
  );
}
